import { NextRequest, NextResponse } from 'next/server'
import { createServerSupabaseClient } from '@/lib/supabase-server'
import { createDSVersion, insertChangelogEntries, updateDSSyncStatus } from '@/lib/ds-connections'
import type {
  DSSyncResult,
  CapsuleRule,
  DSChangeCategory,
  DSChangeType,
} from '@/lib/types/design-system'
import type { Capture } from '@/types/capture'

// ── helpers ──────────────────────────────────────────────────

function hexInStatement(s: string): string | null {
  return s.match(/#[0-9a-fA-F]{3,6}\b/)?.[0] ?? null
}

function whitespacePercent(s: string): string | null {
  return s.match(/(\d+)%\s*(?:whitespace|space|padding|margin)/i)?.[1] ?? null
}

function buildTokensCss(
  rules: CapsuleRule[],
  version: string,
  capsuleVersion: string,
  today: string
): string {
  const colorRules = rules.filter(r => hexInStatement(r.statement))
  const neverGradient = rules.find(r => r.ruleType === 'NEVER' && r.statement.toLowerCase().includes('gradient'))
  const neverShadow = rules.find(r => r.ruleType === 'NEVER' && r.statement.toLowerCase().includes('shadow'))
  const typoRules = rules.filter(r =>
    r.domain.toLowerCase().includes('typ') ||
    r.statement.toLowerCase().includes('font') ||
    r.statement.toLowerCase().includes('typeface') ||
    r.statement.toLowerCase().includes('typograph')
  )
  const spacingRules = rules.filter(r => whitespacePercent(r.statement))

  let css = `/*
 * curato-tokens.css
 * Generated by Curato DS Sync
 * DS Version: ${version} · Capsule: ${capsuleVersion} · ${today}
 *
 * REVIEW BEFORE APPLYING.
 * Copy confirmed values into your tokens/ files.
 * Lines marked MANUAL need human judgment.
 */

:root {
  /* ── COLOR ── */`

  for (const rule of colorRules) {
    const hex = hexInStatement(rule.statement)!
    const label = rule.domain.toLowerCase().replace(/\s+/g, '-')
    const truncated = rule.statement.slice(0, 60)
    css += `\n  --curato-${label}: ${hex}; /* ${rule.ruleType}: ${truncated} */`
  }
  if (neverGradient) css += '\n  /* NEVER: gradients */'
  if (neverShadow)   css += '\n  /* NEVER: shadows */'

  css += '\n\n  /* ── TYPOGRAPHY ── */'
  for (const rule of typoRules) {
    css += `\n  /* ${rule.ruleType}: ${rule.statement} */`
  }
  css += '\n  --curato-font-display: /* MANUAL: set font family */;'
  css += '\n  --curato-font-mono:    /* MANUAL: set monospace font */;'

  css += '\n\n  /* ── SPACING ── */'
  for (const rule of spacingRules) {
    const pct = whitespacePercent(rule.statement)!
    css += `\n  /* Whitespace floor: ${pct}% */`
    css += `\n  --curato-space-layout: /* MANUAL: based on ${pct}% whitespace rule */;`
  }

  css += '\n}\n'
  return css
}

function buildSkillPatch(
  rules: CapsuleRule[],
  declaration: string,
  approvedTags: Array<{ tag: string; count: number }>,
  moodProfile: string[],
  antiSlopScore: number | null,
  version: string,
  capsuleVersion: string,
  today: string
): string {
  const alwaysRules = rules.filter(r => r.ruleType === 'ALWAYS')
  const neverRules  = rules.filter(r => r.ruleType === 'NEVER')
  const prefRules   = rules.filter(r => r.ruleType === 'PREFER' || r.ruleType === 'AVOID')
  const top8        = approvedTags.slice(0, 8)
  const top5Moods   = moodProfile.slice(0, 5)

  let md = `# SKILL.md Taste Constraints Patch
> Curato DS Sync · DS v${version} · Capsule v${capsuleVersion} · ${today}
> Append this section to your SKILL.md after existing component docs.

---

## Taste Constraints

*Anti-slop score: ${antiSlopScore != null ? `${antiSlopScore}` : 'not yet measured'}/100*
`

  if (declaration) {
    md += `
### Aesthetic declaration
> "${declaration}"
`
  }

  if (alwaysRules.length > 0) {
    md += '\n### Always\n'
    for (const r of alwaysRules) md += `- **[${r.domain}]** ${r.statement}\n`
  }

  if (neverRules.length > 0) {
    md += '\n### Never\n'
    for (const r of neverRules) md += `- **[${r.domain}]** ${r.statement}\n`
  }

  if (prefRules.length > 0) {
    md += '\n### Preferences\n'
    for (const r of prefRules) md += `- ${r.ruleType} [${r.domain}]: ${r.statement}\n`
  }

  if (top8.length > 0) {
    md += '\n### Aesthetic anchors\n'
    md += top8.map(t => `\`${t.tag}\` ×${t.count}`).join(' · ') + '\n'
  }

  if (top5Moods.length > 0) {
    md += '\n### Mood profile\n'
    md += top5Moods.join(' · ') + '\n'
  }

  md += '\n---\n'
  return md
}

// ── route ────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  // STEP 1 — Auth
  const supabase = await createServerSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // STEP 2 — Parse body
  const body = await req.json() as {
    ds_connection_id?: string
    capsule_id?: string
    version?: string
    notes?: string
  }
  const { ds_connection_id, capsule_id, version, notes } = body

  if (!ds_connection_id || !capsule_id || !version) {
    return NextResponse.json(
      { error: 'ds_connection_id, capsule_id and version are required' },
      { status: 400 }
    )
  }

  // STEP 3 — Set syncing
  await updateDSSyncStatus(ds_connection_id, 'syncing')

  try {
    // STEP 4 — Load capsule
    const { data: capsuleRow, error: capsuleErr } = await supabase
      .from('capsules')
      .select('*')
      .eq('id', capsule_id)
      .eq('user_id', user.id)
      .single()

    if (capsuleErr || !capsuleRow) {
      await updateDSSyncStatus(ds_connection_id, 'connected')
      return NextResponse.json({ error: 'Capsule not found' }, { status: 404 })
    }

    const [ruleResult, feelingResult, reactionResult] = await Promise.all([
      supabase.from('captures').select('*')
        .eq('user_id', user.id).eq('type', 'rule').eq('verdict', 'keep'),
      supabase.from('captures').select('*')
        .eq('user_id', user.id).eq('type', 'feeling').eq('verdict', 'keep'),
      supabase.from('captures').select('*')
        .eq('user_id', user.id).eq('type', 'reaction').not('verdict', 'is', null),
    ])

    const ruleCaptures    = (ruleResult.data    ?? []) as Capture[]
    const feelingCaptures = (feelingResult.data  ?? []) as Capture[]
    const reactionCaptures = (reactionResult.data ?? []) as Capture[]

    // STEP 5 — Build CapsuleForSync
    const rules: CapsuleRule[] = ruleCaptures.map(c => ({
      id: c.id,
      domain: c.domains?.[0] ?? 'general',
      ruleType: (c.rule_verb ?? 'PREFER') as CapsuleRule['ruleType'],
      statement: c.content ?? '',
      strength: 3,
    }))

    const tagFreq: Record<string, number>    = {}
    const rejTagFreq: Record<string, number> = {}
    for (const c of reactionCaptures) {
      const bucket = c.verdict === 'keep' ? tagFreq : rejTagFreq
      for (const tag of (c.tags ?? [])) bucket[tag] = (bucket[tag] ?? 0) + 1
    }

    const totalRejections = reactionCaptures.filter(c => c.verdict === 'reject').length
    const aiSlopCount     = reactionCaptures.filter(c =>
      c.verdict === 'reject' && (c.tags ?? []).includes('ai-slop')
    ).length
    const antiSlopScore   = totalRejections > 0
      ? Math.min(100, Math.round((aiSlopCount / totalRejections) * 200))
      : null

    const moodTagFreq: Record<string, number> = {}
    for (const c of feelingCaptures) {
      for (const tag of (c.tags ?? [])) moodTagFreq[tag] = (moodTagFreq[tag] ?? 0) + 1
    }
    const moodProfile = Object.entries(moodTagFreq)
      .sort(([, a], [, b]) => b - a)
      .map(([tag]) => tag)

    const approvedTags = Object.entries(tagFreq)
      .sort(([, a], [, b]) => b - a)
      .map(([tag, count]) => ({ tag, count }))

    const rejectedTags = Object.entries(rejTagFreq)
      .sort(([, a], [, b]) => b - a)
      .map(([tag, count]) => ({ tag, count }))

    // STEP 6 — Generate patch content
    const today = new Date().toISOString().split('T')[0]

    const tokensCss = buildTokensCss(rules, version, capsuleRow.version as string, today)
    const skillPatch = buildSkillPatch(
      rules,
      capsuleRow.declaration as string,
      approvedTags,
      moodProfile,
      antiSlopScore,
      version,
      capsuleRow.version as string,
      today
    )

    // STEP 7 — Upload to ds-patches storage
    const storagePath = `${user.id}/${ds_connection_id}/${version}`

    const [tokensUpload, skillUpload] = await Promise.all([
      supabase.storage.from('ds-patches').upload(
        `${storagePath}/curato-tokens.css`,
        new Blob([tokensCss], { type: 'text/css' }),
        { upsert: true }
      ),
      supabase.storage.from('ds-patches').upload(
        `${storagePath}/curato-skill-patch.md`,
        new Blob([skillPatch], { type: 'text/markdown' }),
        { upsert: true }
      ),
    ])

    const tokensCssUrl = tokensUpload.error
      ? null
      : supabase.storage.from('ds-patches')
          .getPublicUrl(`${storagePath}/curato-tokens.css`).data.publicUrl

    const skillPatchUrl = skillUpload.error
      ? null
      : supabase.storage.from('ds-patches')
          .getPublicUrl(`${storagePath}/curato-skill-patch.md`).data.publicUrl

    // STEP 8 — Load previous version for diff (before createDSVersion demotes it)
    const { data: prevVersion } = await supabase
      .from('ds_versions')
      .select('rules_snapshot')
      .eq('ds_connection_id', ds_connection_id)
      .eq('is_current', true)
      .single()

    const previousRules: CapsuleRule[] = (prevVersion?.rules_snapshot ?? []) as CapsuleRule[]
    const prevRuleIds = new Set(previousRules.map((r: CapsuleRule) => r.id))
    const newRules    = rules.filter(r => !prevRuleIds.has(r.id))

    const changelogEntries: Array<{
      category: DSChangeCategory
      change_type: DSChangeType
      description: string
      source?: string
    }> = []

    if (newRules.length > 0) {
      for (const r of newRules) {
        changelogEntries.push({
          category: 'rules',
          change_type: 'added',
          description: `${r.ruleType} [${r.domain}]: ${r.statement}`,
          source: `capsule rule ${r.id}`,
        })
      }
    } else {
      changelogEntries.push({
        category: 'rules',
        change_type: 'unchanged',
        description: `${rules.length} rules — no changes`,
      })
    }

    changelogEntries.push({
      category: 'skill',
      change_type: 'updated',
      description: `SKILL.md Taste Constraints updated from capsule v${capsuleRow.version}`,
    })

    // STEP 9 — createDSVersion + update with patch URLs
    const dsVersion = await createDSVersion(
      user.id,
      ds_connection_id,
      capsule_id,
      version,
      notes ?? null,
      {
        tokens_snapshot: null,
        rules_snapshot: rules,
        feelings_snapshot: null,
        anti_slop_score: antiSlopScore,
      }
    )

    await supabase
      .from('ds_versions')
      .update({ tokens_css_url: tokensCssUrl, skill_patch_url: skillPatchUrl })
      .eq('id', dsVersion.id)

    // STEP 10 — insertChangelogEntries
    await insertChangelogEntries(user.id, dsVersion.id, changelogEntries)

    // STEP 11 — updateDSSyncStatus to connected
    await updateDSSyncStatus(ds_connection_id, 'connected', {
      last_synced_at: new Date().toISOString(),
      last_sync_version: version,
      last_capsule_version: capsuleRow.version as string,
    })

    // STEP 12 — Return DSSyncResult
    const result: DSSyncResult = {
      success: true,
      version_id: dsVersion.id,
      version,
      changelog: changelogEntries.map((e, i) => ({
        id: `${dsVersion.id}-${i}`,
        user_id: user.id,
        version_id: dsVersion.id,
        category: e.category,
        change_type: e.change_type,
        description: e.description,
        before_value: null,
        after_value: null,
        source: e.source ?? 'system',
        created_at: new Date().toISOString(),
      })),
      patch_urls: {
        tokens_css: tokensCssUrl,
        readme: null,
        skill: skillPatchUrl,
        components: null,
        report: null,
      },
      error: null,
    }
    return NextResponse.json(result)
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    await updateDSSyncStatus(ds_connection_id, 'error', { sync_error: message })
    const result: DSSyncResult = {
      success: false,
      version_id: null,
      version: null,
      changelog: [],
      patch_urls: { tokens_css: null, readme: null, skill: null, components: null, report: null },
      error: message,
    }
    return NextResponse.json(result, { status: 500 })
  }
}
